/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PsContactForm {
        "buttonClasses": string;
        "emailPlaceholderText": string;
        "fullNamePlaceholderText": string;
        "inputClasses": string;
        "integrationKey": string;
        "messagePlaceholderText": string;
        "submitButtonText": string;
        "successMessage": string;
        "tags": string;
        "textAreaClasses": string;
    }
}
declare global {
    interface HTMLPsContactFormElement extends Components.PsContactForm, HTMLStencilElement {
    }
    var HTMLPsContactFormElement: {
        prototype: HTMLPsContactFormElement;
        new (): HTMLPsContactFormElement;
    };
    interface HTMLElementTagNameMap {
        "ps-contact-form": HTMLPsContactFormElement;
    }
}
declare namespace LocalJSX {
    interface PsContactForm {
        "buttonClasses"?: string;
        "emailPlaceholderText"?: string;
        "fullNamePlaceholderText"?: string;
        "inputClasses"?: string;
        "integrationKey"?: string;
        "messagePlaceholderText"?: string;
        "onPs-cf-invalid-email-ev"?: (event: CustomEvent<any>) => void;
        "onPs-cf-invalid-fullname-ev"?: (event: CustomEvent<any>) => void;
        "onPs-cf-invalid-message-ev"?: (event: CustomEvent<any>) => void;
        "onPs-cf-submission-error-ev"?: (event: CustomEvent<any>) => void;
        "onPs-cf-submission-ev"?: (event: CustomEvent<any>) => void;
        "onPs-cf-submission-failed-ev"?: (event: CustomEvent<any>) => void;
        "onPs-cf-submission-success-ev"?: (event: CustomEvent<any>) => void;
        "submitButtonText"?: string;
        "successMessage"?: string;
        "tags"?: string;
        "textAreaClasses"?: string;
    }
    interface IntrinsicElements {
        "ps-contact-form": PsContactForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ps-contact-form": LocalJSX.PsContactForm & JSXBase.HTMLAttributes<HTMLPsContactFormElement>;
        }
    }
}
