/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PsContactForm {
        "schema": any;
    }
}
declare global {
    interface HTMLPsContactFormElement extends Components.PsContactForm, HTMLStencilElement {
    }
    var HTMLPsContactFormElement: {
        prototype: HTMLPsContactFormElement;
        new (): HTMLPsContactFormElement;
    };
    interface HTMLElementTagNameMap {
        "ps-contact-form": HTMLPsContactFormElement;
    }
}
declare namespace LocalJSX {
    interface PsContactForm {
        "schema"?: any;
    }
    interface IntrinsicElements {
        "ps-contact-form": PsContactForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ps-contact-form": LocalJSX.PsContactForm & JSXBase.HTMLAttributes<HTMLPsContactFormElement>;
        }
    }
}
